import java.nio.charset.StandardCharsets

object LanguagesTester {
  def main(args: Array[String]) {
    def texts = Map(
      "german" -> "Jeder, der Alten und Mittleren Englisch literarische Texte liest, wird mit derh Mitte der braunen Bände des EETS, mit dem Symbol des Alfred Juwel geprägt auf der Vorderseite vertraut sein. Die meisten Werke zugeschrieben König Alfred oder zu Aelfric, zusammen mit einigen der von Bischof Wulfstan und viel anonymen Vers und Prosa aus der Pre-Conquest Zeitraum, sind innerhalb der Society drei Serien zu finden; alle überlebenden mittelalterlichen Drama, die meisten der mittelenglischen Romanzen, viel religiöse und weltliche Prosa und Versen, einschließlich der englischen Werke von John Gower, Thomas Hoccleve und die meisten Drucke Caxtons alle ihren Platz in den Publikationen. Ohne EETS Ausgaben, Studium der mittelalterlichen englischen Texte wäre kaum möglich sein.",
      "english" -> "Anyone who reads Old and Middle English literary texts will be familiar with the mid-brown volumes of the EETS, with the symbol of Alfred's jewel embossed on the front cover. Most of the works attributed to King Alfred or to Aelfric, along with some of those by bishop Wulfstan and much anonymous prose and verse from the pre-Conquest period, are to be found within the Society's three series; all of the surviving medieval drama, most of the Middle English romances, much religious and secular prose and verse including the English works of John Gower, Thomas Hoccleve and most of Caxton's prints all find their place in the publications. Without EETS editions, study of medieval English texts would hardly be possible.",
      "finnish" -> "Jokainen, joka lukee vanhan ja Lähi Englanti kirjallisuuden teksteistä tuntee puolivälissä ruskeat volyymit EETS, tunnuksella Alfred n helmi painettu etukansi. Suurin osa teoksista johtuvan kuningas Alfred tai Aelfric, yhdessä joidenkin niistä piispa Wulfstan ja paljon nimetön proosaa ja jae edeltävästä Conquest aikana, löytyvät sisällä seuran kolme sarjaa; kaikki elossa keskiaikainen draama, suurin osa Lähi Englanti romansseja, paljon uskonnollisten ja maallisten proosaa ja jae lukien Englanti teoksia John Gower, Thomas Hoccleve ja useimmat Caxton n tulostaa kaikki löytää paikkansa julkaisuissa. Ilman EETS painokset, tutkimus keskiaikainen Englanti tekstien tuskin onnistuisi.",
      "italian" -> "Chiunque legga vecchi e Medio inglese testi letterari avranno familiarità con i volumi metà marroni del SET, con il simbolo del gioiello di Alfred in rilievo sulla copertina. La maggior parte delle opere attribuite a re Alfredo o Aelfric, insieme ad alcuni di quelli dal vescovo Wulfstan e molto in prosa e in versi anonimi dal periodo pre-Conquista, si trovano all'interno di tre serie della Società; tutto il dramma medievale sopravvissuta, la maggior parte dei romanzi Medio inglese, molto prosa religiosa e secolare e versi tra cui le opere in inglese di John Gower, Thomas Hoccleve e la maggior parte delle stampe di Caxton tutti trovano il loro posto nelle pubblicazioni. Senza edizioni del SET, studio dei testi medievali inglesi sarebbe difficilmente possibile.",
      "spanish" -> "Cualquiera que lea inglés antiguo y medio textos literarios estará familiarizado con los volúmenes mediados de marrón de la SET, con el símbolo de la joya de Alfred en relieve en la cubierta frontal. La mayor parte de las obras que se atribuyen al rey Alfredo o para Aelfrico, junto con algunos de los que por el obispo Wulfstan y mucho prosa y verso anónimo de la época anterior a la conquista, se encuentran dentro de tres series de la Sociedad; todo el drama medieval sobrevivir, la mayoría de los romances del inglés medio, tanto en prosa religiosa y secular y el verso que incluye las obras en inglés de John Gower, Thomas Hoccleve y la mayor parte de los grabados de Caxton todos encuentran su lugar en las publicaciones. Sin ediciones del SET, el estudio de los textos medievales ingleses difícilmente sería posible.",
      "polish" -> "Każdy, kto czyta literackich tekstów Starego i Bliski angielskiego będzie zaznajomiony z mid-brązowych tomów EETS, z symbolem klejnotu Alfreda wytłoczonym na okładce. Większość prac przypisywanych króla Alfreda lub Aelfric, wraz z niektórymi z tych bp Wulfstana i wiele anonimowych prozą i wierszem z okresu sprzed podboju znajdują się w obrębie trzech seriach Towarzystwa; wszystkich zachowanych średniowiecznych dramatu, większość romansów Bliski angielskich, podobnie prozy i poezji religijnej i świeckiej, w tym angielskich dzieł Jana Gower, Thomas Hoccleve i większość Caxtona za odbitki wszystkich znaleźć swoje miejsce w publikacjach. Bez edycjach EETS, badanie średniowiecznych tekstach angielskich raczej nie będzie możliwe."
    )
    for (i <- 1 to 10) {
      texts.foreach({ case (language, text) => {
        LanguageGuesser.calculateAllGuesses(language, i, text.split("\\W+"))
      }
      })
    }
  }

}
